//Play Video function
var promo = "<div class='videoContainer'<div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var LourdesVid1 = "<div class='videoCell two'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var LourdesVid2 = "<div class='videoCell three'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var ShikoVid1 = "<div class='videoCell two'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var ShikoVid2 = "<div class='videoCell three'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var JerusalemVid1 = "<div class='videoCell two'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var JerusalemVid2 = "<div class='videoCell three'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var HajjVid1 = "<div class='videoCell two'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var HajjVid2 = "<div class='videoCell three'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var KumbhVid1 = "<div class='videoCell two'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var KumbhVid2 = "<div class='videoCell three'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var NigeriaVid1 = "<div class='videoCell two'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"
var NigeriaVid2 = "<div class='videoCell three'><div class='cove-box'><iframe id='partnerPlayer' frameborder='0' marginwidth='0' marginheight='0' scrolling='no' src='http://video.pbs.org/widget/partnerplayer/2365050419/?w=1383&h=900&chapterbar=true&autoplay=true&endscreen=false'></iframe></div></div>"

function playVideo(element,video) {
	$(element).empty();
	$(element).append(video);
	$(element).css('background-color','transparent')
};
